[package]
name = "ssri"
version = "7.0.1-alpha.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"
description = "Various utilities for handling Subresource Integrity."
license = "Apache-2.0"
repository = "https://github.com/zkat/ssri-rs"
homepage = "https://github.com/zkat/ssri-rs"
readme = "README.md"

[dependencies]
sha2 = "0.10"
base64 = "0.10.1"
digest = "0.10"
sha-1 = "0.10"
hex = "0.3.2"
serde = { version = "1.0.92", optional = true }
thiserror = "1.0.38"

[features]
default = ["serde"]

[dev-dependencies]
serde_json = "1.0.57"
serde_derive = "1.0.115"
